// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGJJ2St1rWnDUnbg7UxfB_7hX2Mt4Rsk',
    appId: '1:501669670766:web:811266c72fa272ffdb9b7f',
    messagingSenderId: '501669670766',
    projectId: 'social-767a8',
    authDomain: 'social-767a8.firebaseapp.com',
    storageBucket: 'social-767a8.appspot.com',
    measurementId: 'G-433YFGZ687',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8DGJ4xyrBrfXBkKqP4oJLxzBQEOO5gwY',
    appId: '1:501669670766:android:f6282e70cb150a0ddb9b7f',
    messagingSenderId: '501669670766',
    projectId: 'social-767a8',
    storageBucket: 'social-767a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzHWUbwbl0NPkyMuE_uMDH2IVjIl8Fi8',
    appId: '1:501669670766:ios:739926df99f8498fdb9b7f',
    messagingSenderId: '501669670766',
    projectId: 'social-767a8',
    storageBucket: 'social-767a8.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXzHWUbwbl0NPkyMuE_uMDH2IVjIl8Fi8',
    appId: '1:501669670766:ios:739926df99f8498fdb9b7f',
    messagingSenderId: '501669670766',
    projectId: 'social-767a8',
    storageBucket: 'social-767a8.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvGJJ2St1rWnDUnbg7UxfB_7hX2Mt4Rsk',
    appId: '1:501669670766:web:1d5951357a4d3b88db9b7f',
    messagingSenderId: '501669670766',
    projectId: 'social-767a8',
    authDomain: 'social-767a8.firebaseapp.com',
    storageBucket: 'social-767a8.appspot.com',
    measurementId: 'G-VBN1YCQJV2',
  );
}
